### ISSUE TITLE
Fix how stars are treated...

### ISSUE THREAD

**Issue by slosar** [DarkEnergyScienceCollaboration/2pt_validation#23]
Colore changes, dtype changes, shit hits the fan, need a more robust way of handling this.
See readstars in subs.py in fastcat_Colore

**Comment by slosar** [comment]
Will go straight to sampling stars from healpix file.

@fjaviersanchez , to remind you, here is your email from jul 25:

> Hello,
> 
> The script is attached. What I do is to get random positions from a higher
> resolution nested healpix map. I think this is the fastest way to do it.
> You can change the healpix map resolution if you want less stars to be in
> the same positions (it is unlikely with 2M stars but if we go to higher
> stellar densities it might happen) or add certain gaussian around the
> center of these positions.

A couple of issues:
- I have the script, but I need the file
- I plotted the 2M stars that you sent and they look a bit dodgy, see the attached plot: in the upper right part, there is a clear galactic "finger" but not stars -- is this known? Not a big issue for code testing, but would be good to understand
- Also, we need to perturb stars around their nominal position in pixel, othewise you pixelate at 1024 and get weird stripes...

![shot](https://cloud.githubusercontent.com/assets/1197186/18049194/b5a99ccc-6db4-11e6-820e-719cd02c546b.png)

**Comment by danielsf** [comment]
What are the requirements on this stellar population?  CatSim contains a simulated Milky Way generated with Mario Juric's GalFast code.  Perhaps that could be of some use?

**Comment by fjaviersanchez** [comment]
@slosar 
- I think that finger on the right is the part of the MW Survey but there are no other fields covered, whereas in the left there are fields from the main survey. And the part at the center of the galactic plane o the right I don't remember if it wasn't simulated or it won't be covered. Maybe @danielsf can clarify this?
- I will try to do the perturbation around those positions to avoid the stripes. Also, how many stars do you think we need for our exercise, 10M? I will generate a new file with these stars and send it to you. (Or do you need the healpix density maps instead?)

@danielsf 

We decided to use the MAF maps from the CatSim stars because we wanted a realistic distribution of densities as a function of position, and downloading the whole stellar population from CatSim was really slow. We don't need all the stars in the catalog, just a subsample to see their effect in the clustering signal but, we need the whole LSST footprint.

**Comment by slosar** [comment]
@fjaviersanchez 
Thanks for your emails today. As you say, what i though is an issue, is not an issue at all, since that finger is outside the region anway, see the shot below.
I will just use your code and generate those stars on the fly rather than move around this massive file...

![shot](https://cloud.githubusercontent.com/assets/1197186/18121323/09352a54-6f32-11e6-8c95-0c050593649b.png)

**Comment by slosar** [comment]
@fjaviersanchez @danielsf 
Great, I ported this code to fastcat, now all makes much more sense.
